INSERT INTO TBinformation2 (
    IDinformation2,
    Province,
    Department,
    IDinformation1
    )
    VALUES (
        1,
        'Paranaque',
        'Engineering',
        1
    );
GO

INSERT INTO TBinformation2 (
    IDinformation2,
    Province,
    Department,
    IDinformation1
    )
    VALUES (
        2,
        'Cavite',
        'IT',
        2
    );
GO

INSERT INTO TBinformation2 (
    IDinformation2,
    Province,
    Department,
    IDinformation1
    )
    VALUES (
        3,
        'Laguna',
        'Legal',
        3
    );
GO

INSERT INTO TBinformation2 (
    IDinformation2,
    Province,
    Department,
    IDinformation1
    )
    VALUES (
        4,
        'Laguna',
        'Accountancy',
        4
    );
GO