INSERT INTO Table1 (
    Name,
    City,
    Type
)

VALUES (
        'Corazon Aquino',
        'Quezon',
        'A'
    ),
    (
        'Fidel Ramos',
        'Caloocan',
        'B'
    ),
    (
        'Gloria Arroyo',
        'Pasig',
        'C'
    );
/****Note that i did not include the CustID number because if the "IDENTITY" Function upon creating the table 1****/
/**** This also apply to Table2*****/


GO
